config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories,       only: [:index, :show]
  resources :discussions,      only: [:show]
  resources :search,           only: [:index]
  resources :users,            only: [:show] do
    get     'discussions',     to: 'users#discussions', as: 'discussions'
    get     'comments',        to: 'users#comments',    as: 'comments'
  end
  resources :badges,           only: [:show]
  get       'tagged/(:tag)',   to: 'tags#show', as: 'tag'

  # backwards compatibility with vanilla URL scheme:
  get       'index.php',       to: 'redirect#redirect'

  # route anything else to a custom 404
  match     '*p',              to: "application#routing_error", via: :get
  get       'bad_route/(:id)', to: "application#bad_format_routing_error"
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  self.table_name = 'GDN_Discussion'
  self.primary_key = :DiscussionID

  belongs_to :category,    foreign_key: :CategoryID
  has_many   :comments,    -> {
    order('DateInserted asc')
  }, foreign_key: :DiscussionID
  has_one    :creator,     class_name: 'User', primary_key: :InsertUserID, foreign_key: :UserID
  has_one    :last_user,   class_name: 'User', primary_key: :LastCommentUserID, foreign_key: :UserID
  has_many   :attachments, -> { Attachment.active.discussion }, foreign_key: :ForeignID

  scope :sorted, -> { order(Arel.sql("FIELD(Announce,0) asc, DateLastComment desc, DateInserted desc")) }
  scope :search, lambda { |term|
    where('match(Name, Body) against(?)', term).
    where('Name != ?', 'The user and all related content has been deleted.').
    where('Body != ?', 'The user and all related content has been deleted.')
  }
  scope :tagged, lambda { |tag|
    where('UPPER(Tags) like ?', "%#{tag.to_s.upcase}%")
  }

  alias_attribute :name,            :Name
  alias_attribute :body,            :Body
  alias_attribute :created,         :DateInserted
  alias_attribute :updated,         :DateUpdated
  alias_attribute :announce,        :Announce
  alias_attribute :closed,          :Closed
  alias_attribute :view_count,      :CountViews
  alias_attribute :comment_count,   :CountComments
  alias_attribute :last_posted,     :DateLastComment
  alias_attribute :last_comment_id, :LastCommentID
  alias_attribute :tags,            :Tags
  alias_attribute :format,          :Format

  def announcement?
    announce > 0
  end

  def closed?
    closed == 1
  end

  def tag_list
    Rails.cache.fetch("discussion_#{id}_tags", expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL) do
      tag_list = []
      tags.blank? and return tag_list
      # sometimes tags are separated by commas, sometimes by spaces, sometimes
      # comma separated tags HAVE spaces.
      # additionally, most tags are strings, but some tags are integers that
      # point at a Tag object.
      # fun for the whole family.
      raw_tag_list = []
      if tags =~ /,/
        raw_tag_list = tags.split(',')
      else
        raw_tag_list = tags.split(/\s/)
      end
      raw_tag_list.each do |t|
        t.squish!
        t.blank? and next
        if t =~ /\A[0-9]+\z/
          tag_name = Tag.find_by(TagId: t)
          tag_name.blank? and next
          tag_list << tag_name.full_name
        else
          tag_list << t
        end
      end
      tag_list
    end
  end

  # will return the number of pages will_paginate will break this discussion's
  # comments into
  def num_comment_pages
    Rails.cache.fetch("discussion_#{id}_num_pages", expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL) do
      (comments.size/PER_PAGE_MAX.to_f).ceil
    end
  end

  # given a comment ID, will return the page number that comment will appear on
  # in this discussion's paginated comments
  def comment_page(comment_id)
    Rails.cache.fetch("comment_#{comment_id}_page", expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL) do
      comment_ids = comments.collect(&:id)
      index = comment_ids.find_index(comment_id.to_i)
      index.blank? and return 1
      (index/PER_PAGE_MAX)+1
    end
  end

end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  caches_action :show, expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL, cache_path: Proc.new { |c| "#{c.params[:id]}_#{c.params[:page].to_i}" }

  def show
    params[:page] ||= '1'
    (params[:page].to_i > 0) or params[:page] = '1'
    @discussion = Discussion.find(params[:id])
    @page_title = @discussion.name
  end
  
end

app/helpers/discussions_helper.rb
module DiscussionsHelper

  # will display large numbers of views in a shortened fashion
  def view_count(count)
    if count > 1000
      rounded_count = sprintf "%.1f", (count.to_f/1000)
      rounded_count.gsub!(/\.0/, '')
      "#{rounded_count}K"
    else
      count
    end
  end

  # Discussions and Comments have content in one of the following formats:
  #   "Html", "TextEx", "Markdown", "Deleted"
  # given raw content, generate an output rails can use
  def format_post(format, raw_content, attachments, truncate = false)
    content = raw_content
    # any links to other forum posts need to be updated
    content.gsub!(/https:\/\/forum.biohack.me\/index.php\?p=\/discussion\/([0-9]+)\/[-_0-9A-Za-z]+/) do |match|
      discussion_id = $1
      discussion_path(discussion_id, page: 1)
    end
    # ditto any links to uploaded forum media
    content.gsub!(/https:\/\/forum.biohack.me\/uploads\/editor\/([-_\/.A-Za-z0-9]*)/) do |match|
      image_path = $1
      image_path("uploads/#{image_path}")
    end
    output = ''
    case format
    when 'Html'
      output = sanitize(auto_link(content, sanitize: false, html: { rel: 'nofollow' }), tags: %w(strong em a p br img ul ol li br div object param embed), attributes: %w(href src target rel alt width height class style name value type allowfullscreen allowScriptAccess))
    when 'TextEx'
      output = simple_format(auto_link(content, html: { rel: 'nofollow' }))
    when 'Markdown'
      options = {
        filter_html: true,
        hard_wrap: true,
        link_attributes: { rel: 'nofollow' },
        space_after_headers: true,
        fenced_code_blocks: true
      }
      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, autolink: true)
      output = markdown.render(content).html_safe
    when 'Deleted'
      output = content_tag(:em, "The user and all related content has been deleted.")
    else
      output = content_tag(:em, "Unknown post format!")
    end
    # auto link @usernames
    begin
      output.gsub!(/@([-_A-Za-z0-9]+)/) do |match|
        username = $1
        disp_username = "@#{username}"
        user = User.where(name: username).first
        if user && !user.deleted? && !user.private?
          link_to disp_username, user_path(user.id)
        else
          disp_username
        end
      end
    rescue ArgumentError => e
      # some content was causing the @username match gsub to fail with
      # `ArgumentError (invalid byte sequence in UTF-8)` - don't make the app
      # crash over this, but log it
      logger.error "************ the following content failed with #{e.message} (#{e.class}):\n#{output}"
    end
    unless attachments.empty?
      output << "<ul class='attachments'>"
      attachments.each do |attachment|
        attachment_link = begin
                            asset_path(attachment.path)
                          rescue
                            false
                          end
        if attachment_link
          output << "<li id='#{attachment.id}'>"
          thumb_path = attachment.is_image? ? attachment.thumb_path : 'file.png'
          output << '<div class="preview">'
          output << link_to(image_tag(thumb_path, alt: attachment.name, title: attachment.name, width: 30, height: 30, loading: 'lazy'), attachment_link, target: '_blank')
          output << '</div>'
          output << '<div class="details">'
          output << link_to(attachment.name.truncate(24), attachment_link, target: '_blank')
          output << '<div class="file_size">'
          output << number_to_human_size(attachment.size)
          output << '</div>'
          output << '</div>'
          output << '</li>'
        end
      end
      output << "</ul>"
    end
    if truncate
      strip_tags(output).truncate(truncate).html_safe
    else
      output.html_safe
    end
  end

end

app/views/discussions/_preview.html.haml
.clear.vertical_spacer
- if show_author
  .avatar
    = user_avatar_link_unless_private(discussion.creator)
.discussion_preview  
  .name
    = link_to discussion.name, discussion_path(discussion.id, page: 1)
  .flags
    %ul
      - if discussion.announcement?
        %li Announcement
      - if discussion.closed?
        %li Closed
  - if show_author
    .author
      = user_link_unless_private(discussion.creator)
  .date
    = date_disp(discussion.created)
  .views
    #{view_count(discussion.view_count)} views
  .comments
    = pluralize(discussion.comment_count, 'comment')
  - if discussion.last_user
    .last_comment
      Most recent by #{user_link_unless_private(discussion.last_user)}
      - if !discussion.last_posted.blank?
        = (discussion.last_posted > Date.today-1.year) ? 'on ' : 'in '
        = link_to date_disp(discussion.last_posted), discussion_path(discussion.id, page: discussion.num_comment_pages, anchor: discussion.last_comment_id)
  - if show_cat
    .category
      = link_to discussion.category.name, category_path(discussion.category.id)
.clear.vertical_spacer

app/views/discussions/show.html.haml
= content_for :meta do
  %meta{property: 'og:site_name', content: SITE_TITLE}/
  %meta{property: 'og:type', content: 'website'}/
  -unless @discussion.attachments.empty?
    - if @discussion.attachments.first.is_image?
      %meta{property: 'og:image', content: asset_url(@discussion.attachments.first.path)}/
  %meta{property: 'og:url', content: discussion_url(@discussion.id, page: params[:page].to_i)}/
  %meta{property: 'og:title', content: @page_title}/
  %meta{property: 'og:description', content: format_post(@discussion.format, @discussion.body, [], 350)}/
  %meta{property: 'og:article:section', content: @discussion.category.name}/
  %meta{property: 'article:published_time', content: @discussion.created.to_fs(:c)}/
%h1
  = @page_title
- unless (!params[:page].blank? && params[:page].to_i > 1)
  .discussion_post
    = render partial: 'users/author', locals: { user: @discussion.creator }
    .post_metadata
      .date_posted
        = date_disp(@discussion.created)
      - if @discussion.updated
        .date_edited
          edited #{date_disp(@discussion.updated)}
      .category
        in #{link_to @discussion.category.name, category_path(@discussion.category.id)}
    .post_body
      = format_post @discussion.format, @discussion.body, @discussion.attachments
    - unless @discussion.tag_list.empty?
      .post_tags
        Tagged:
        - tag_links = []
        -  @discussion.tag_list.each do |tag|
          - tag_links << link_to(tag,tag_path(tag))
        = tag_links.join(', ').html_safe

- unless @discussion.comments.blank?
  .clear.vertical_spacer
  %h2 Comments
  - comments = @discussion.comments.paginate(per_page: PER_PAGE_MAX, page: params[:page].to_i)
  .pagination_container
    .page_info
      = page_entries_info comments, entry_name: 'comment'
    = will_paginate comments
  %ol.discussion_comments
    - comments.each do |comment|
      %li.discussion_comment
        - if comment == @discussion.comments.last
          %a{name: 'latest'}
        %a{name: comment.id}
        = render partial: 'users/author', locals: { user: comment.creator }
        .post_metadata
          .date_posted
            = date_disp(comment.created)
          - if comment.updated
            .date_edited
              edited #{date_disp(comment.updated)}
        .post_body
          = format_post comment.format, comment.body, comment.attachments
  .pagination_container
    .page_info
      = page_entries_info comments, entry_name: 'comment'
    = will_paginate comments

  .clear.vertical_spacer

  - if (@discussion.num_comment_pages > 1) && (params[:page].blank? || (params[:page].to_i < @discussion.num_comment_pages))
    = javascript_tag nonce: true do
      :plain
        $(document).ready(function() {
          const anchor = window.location.hash;
          if (anchor == '#latest') {
            console.log('Redirecting to last page/comment...');
            window.location.href = '#{discussion_path(@discussion.id, page: @discussion.num_comment_pages, anchor: @discussion.last_comment_id)}';
          }
        });