config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories,       only: [:index, :show]
  resources :discussions,      only: [:show]
  resources :search,           only: [:index]
  resources :users,            only: [:show] do
    get     'discussions',     to: 'users#discussions', as: 'discussions'
    get     'comments',        to: 'users#comments',    as: 'comments'
  end
  resources :badges,           only: [:show]
  get       'tagged/(:tag)',   to: 'tags#show', as: 'tag'

  # backwards compatibility with vanilla URL scheme:
  get       'index.php',       to: 'redirect#redirect'

  # route anything else to a custom 404
  match     '*p',              to: "application#routing_error", via: :get
  get       'bad_route/(:id)', to: "application#bad_format_routing_error"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @users = []
    @results = []

    if params[:s] && !params[:s].empty?
      # search users
      @users = User.find_by_username(params[:s])

      # search discussions and comments
      @results << Discussion.search(params[:s])
      @results << Comment.search(params[:s])
      @results.flatten!
    end

  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_comment.html.haml
.clear.vertical_spacer
.comment_details
  .name
    Re:
    = link_to comment.discussion.name, discussion_path(comment.discussion.id, page: comment.discussion.comment_page(comment.id), anchor: comment.id)
  .avatar
    = user_avatar_link_unless_private(comment.creator)
  .comment_preview
    .author
      by
      = user_link_unless_private(comment.creator)
    .category
      in
      = link_to comment.discussion.category.name, category_path(comment.discussion.category.id)
    .date
      = date_disp(comment.created)
    .comments_nippit
      = format_post(comment.format, comment.body, [], 350)
.clear.vertical_spacer

app/views/search/_discussion.html.haml
.clear.vertical_spacer
.discussion_details
  .name
    = link_to discussion.name, discussion_path(discussion.id, page: 1)
  .avatar
    = user_avatar_link_unless_private(discussion.creator)
  .discussion_preview
    .author
      by
      = user_link_unless_private(discussion.creator)
    .category
      in
      = link_to discussion.category.name, category_path(discussion.category.id)
    .date
      = date_disp(discussion.created)
    .discussion_snippit
      = format_post(discussion.format, discussion.body, [], 350)
.clear.vertical_spacer

app/views/search/_user.html.haml
.clear.vertical_spacer
.user_details{id: "user_#{user.id}"}
  .avatar{title: user.name}
    = user_avatar_link_unless_private(user)
  .user_preview  
    .name
      = user_link_unless_private(user)
    - unless user.private?
      = render partial: 'users/user_metadata', locals: { user: user }
    .badges
      - user.user_badges.sorted.each do |userbadge|
        - badge = userbadge.badge
        = link_to image_tag(badge.image_path, alt: badge.name, title: badge.name, width: 24, height: 24, loading: 'lazy'), badge_path(badge.id)
.clear.vertical_spacer

app/views/search/index.html.haml
.search_form
  = form_tag search_index_path, method: 'get', role: 'search' do
    = text_field_tag :s, params[:s], autocomplete: 'off', title: 'Search archive', placeholder: 'Search archive'

- unless params[:s].blank?
  - if @users.empty? && @results.empty?
    %p
      No results for <strong>#{params[:s]}</strong>.
  - else
    - if !@users.empty?
      %h2
        #{pluralize @users.size, 'user'} like '#{params[:s]}'
      %ol.search_results
        - @users.each do |user|
          %li
            = render partial: 'user', locals: { user: user }
    - if !@results.empty?
      %h2
        #{pluralize @results.size, 'post'} containing '#{params[:s]}'
      %ol.search_results
        - @results.each do |result|
          %li
            - if result.is_a?(Discussion)
              = render partial: 'discussion', locals: { discussion: result }
            - elsif result.is_a?(Comment)
              - result.discussion or next
              = render partial: 'comment', locals: { comment: result }