config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories,       only: [:index, :show]
  resources :discussions,      only: [:show]
  resources :search,           only: [:index]
  resources :users,            only: [:show] do
    get     'discussions',     to: 'users#discussions', as: 'discussions'
    get     'comments',        to: 'users#comments',    as: 'comments'
  end
  resources :badges,           only: [:show]
  get       'tagged/(:tag)',   to: 'tags#show', as: 'tag'

  # backwards compatibility with vanilla URL scheme:
  get       'index.php',       to: 'redirect#redirect'

  # route anything else to a custom 404
  match     '*p',              to: "application#routing_error", via: :get
  get       'bad_route/(:id)', to: "application#bad_format_routing_error"
end

app/models/user.rb
class User < ApplicationRecord
  self.table_name = 'GDN_User'
  self.primary_key = :UserID

  has_many   :discussions, foreign_key: :InsertUserID
  has_many   :comments,    foreign_key: :InsertUserID
  has_many   :user_badges, foreign_key: :UserID
  has_many   :badges,      through: :user_badges
  has_many   :user_roles,  foreign_key: :UserID
  has_many   :roles,       through: :user_roles
  has_many   :user_meta,   class_name: 'UserMeta', foreign_key: :UserID

  scope :find_by_username, lambda { |name|
    where('UPPER(Name) like ?', "%#{name.upcase}%").
    where('Name != ?', '[Deleted User]').
    order('Name asc')
  }
  scope :active,           -> { where('deleted != 1') }
  scope :profile_metadata, -> { includes(:roles, :user_meta, user_badges: [:badge], discussions: [:category, :creator, :last_user, :comments], comments: [:creator, discussion: [:category]]) }
  scope :with_discussions, -> { includes(discussions: [:category, :creator, :last_user, :comments]) }
  scope :with_comments,    -> { includes(comments: [:creator, discussion: [:category]]) }

  alias_attribute :name,            :Name
  alias_attribute :photo,           :Photo
  alias_attribute :email,           :Email
  alias_attribute :about,           :About
  alias_attribute :created,         :DateInserted
  alias_attribute :visit_count,     :CountVisits
  alias_attribute :last_active,     :DateLastActive
  alias_attribute :points,          :Points
  alias_attribute :show_email,      :ShowEmail
  alias_attribute :raw_attributes,  :Attributes
  alias_attribute :raw_preferences, :Preferences
  alias_attribute :deleted,         :Deleted

  def photo_url(size = 'small')
    Rails.cache.fetch("user_#{id}_photo_#{size}", expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL) do
      # avatars uploaded to vanilla will be stored in GDN_User.photo as,
      #   'userpics/F2IH2KPW2RWL/GBH6RG50OK5K.png'
      # but this will expand to several files, like:
      #   userpics/F2IH2KPW2RWL/nGBH6RG50OK5K.png PNG 40x40 40x40+0+0 8-bit sRGB 4240B 0.000u 0:00.001
      #   userpics/F2IH2KPW2RWL/pGBH6RG50OK5K.png PNG 250x250 250x250+0+0 8-bit sRGB 116627B 0.000u 0:00.000
      # sometimes these are directly under userpics/, sometimes there is an
      # intermediary directory
      # if 'size' requested is 'small' (the default), prepend 'n' to the image
      # filename, otherwise prepent 'p'
      if (photo =~ /\Auserpics\//)
        prefix = (size == 'small') ? 'n' : 'p'
        photo.gsub(/\/(\w+\.[A-Za-z]{3,4})\z/, "/#{prefix}"+'\1')

      # if the photo is to an external URL, it will work or it won't
      elsif (photo =~ /\Ahttps?:\/\//)
        photo

      # if there is no photo, or if the photo is something unexpected
      # (not in userpics/ and not an external URL), try gravatar, falling back to
      # a DiceBear Bottts avatar using the email hash as a seed
      else
        email_hash = Digest::MD5.hexdigest(email.downcase)
        dicebear_fallback = ERB::Util.url_encode("https://api.dicebear.com/8.x/bottts/png/seed=#{email_hash}")
        gravatar_size = (size == 'small') ? '40' : '200'
        "https://gravatar.com/avatar/#{email_hash}?s=#{gravatar_size}&d=#{dicebear_fallback}"
      end
    end
  end

  def show_email?
    show_email == 1
  end

  def private?
    Rails.cache.fetch("user_#{id}_private", expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL) do
      attributes.is_a?(Hash) or return false
      attributes['Private'] == '1'
    end
  end

  def deleted?
    Rails.cache.fetch("user_#{id}_deleted", expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL) do
      deleted == 1
    end
  end

  def pronouns
    user_pronouns = user_meta.type('Profile.Pronouns').first
    user_pronouns ? user_pronouns.value : ''
  end

  def skills
    user_skills = user_meta.type('Profile.Skills').first
    user_skills ? user_skills.value : ''
  end

  private

  # vanilla stores random JSON data in a few text fields - parse them in case
  # something in there is needed
  # parse_json() is defined in ApplicationRecord
  def attributes
    parse_json(raw_attributes)
  end
  def preferences
    parse_json(raw_preferences)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  caches_action :show,        expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL
  caches_action :discussions, expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL
  caches_action :comments,    expires_in: CACHE_TIME, race_condition_ttl: CACHE_TTL

  def show
    @user = User.profile_metadata.find(params[:id])
    @page_title = @user.name
  end

  def discussions
    @user = User.with_discussions.find(params[:user_id])
    render 'users/_user_discussions', layout: false
  end

  def comments
    @user = User.with_comments.find(params[:user_id])
    render 'users/_user_comments', layout: false
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_author.html.haml
.clear.vertical_spacer
.post_author
  .avatar
    = user_avatar_link_unless_private(user)
  .user_preview  
    .name
      = user_link_unless_private(user)
    .badges
      - if user
        - user.user_badges.sorted.each do |userbadge|
          - badge = userbadge.badge
          = link_to image_tag(badge.image_path, alt: badge.name, title: badge.name, width: 24, height: 24, loading: 'lazy'), badge_path(badge.id)

app/views/users/_user_comments.html.haml
%ol.comments
  - @user.comments.sorted.each do |comment|
    - comment.discussion or next
    %li
      = render partial: 'comments/preview', locals: { comment: comment }

app/views/users/_user_discussions.html.haml
%ol.discussions
  - @user.discussions.sorted.each do |discussion|
    %li
      = render partial: 'discussions/preview', locals: { discussion: discussion, show_author: false, show_cat: true }

app/views/users/_user_metadata.html.haml
%dl.about

  - if user.show_email?
    %dt.email
      Email
    %dd.email
      = mail_to user.email

  %dt.joined
    Joined
  %dd.joined
    = date_disp(user.created)

  %dt.visits
    Visits
  %dd.visits
    = user.visit_count

  - if user.last_active
    %dt.last_active
      Last active
    %dd.last_active
      = date_disp(user.last_active)

  %dt.roles
    Roles
  %dd.roles
    = user.roles.collect(&:name).join(', ')

  - if user.points > 0
    %dt.points
      Points
    %dd.points
      = user.points

  - if !user.pronouns.blank?
    %dt.pronouns
      Pronouns
    %dd.pronouns
      = user.pronouns

  - if !user.skills.blank?
    %dt.skills
      Skills
    %dd.skills
      = user.skills

  %dt.badges
    Badges
  %dd.badges
    = user.user_badges.size

app/views/users/show.html.haml
- if @user.deleted?
  %p
    The content you were looking for has been deleted
- elsif @user.private?
  %p
    #{@user.name}'s profile is private
- else
  = content_for :meta do
    %meta{property: 'og:site_name', content: SITE_TITLE}/
    %meta{property: 'og:type', content: 'website'}/
    - photo_url = @user.photo_url('big')
    - unless photo_url =~ /\Ahttp/
      - photo_url = asset_url(photo_url)
    %meta{property: 'og:image', content: photo_url}/
    %meta{property: 'og:url', content: user_url(@user.id)}/
    %meta{property: 'og:title', content: @user.name}/
    %meta{property: 'og:description', content: @user.about}/
  = javascript_include_tag :users
  .user_header
    .avatar{title: @user.name}
      = image_tag(@user.photo_url('big'), alt: @user.name, width: 200, loading: 'lazy')
    .user_details

      %h1.name
        = @user.name

      - if !@user.about.blank?
        .user_bio
          = simple_format @user.about

      = render partial: 'user_metadata', locals: { user: @user }

      .badges
        - @user.user_badges.sorted.each do |userbadge|
          - badge = userbadge.badge
          = link_to image_tag(badge.image_path, alt: badge.name, title: badge.name, width: 32, height: 32, loading: 'lazy'), badge_path(badge.id)

  .clear.vertical_spacer

  .user_activity

    - if @user.discussions.size > 0
      .content_heading
        %h2
          Discussions (#{@user.discussions.size})
        .toggle_link
          = link_to "show discussions", '#', id: "toggle_discussions"
      #user_discussions{class: 'hidden'}
        - if @user.discussions.size < 50
          = render partial: 'user_discussions'
        - else
          = image_tag "spinner.gif", alt: 'loading...', width: 200, height: 200
          = javascript_tag nonce: true do
            :plain
              $("#user_discussions").load("#{user_discussions_path(@user)}");

    .clear.vertical_spacer

    - if @user.comments.size > 0
      .content_heading
        %h2
          Comments (#{@user.comments.size})
        .toggle_link
          = link_to "show comments", '#', id: "toggle_comments"
      #user_comments{class: 'hidden'}
        - if @user.comments.size < 150
          = render partial: 'user_comments'
        - else
          = image_tag "spinner.gif", alt: 'loading...', width: 200, height: 200
          = javascript_tag nonce: true do
            :plain
              $("#user_comments").load("#{user_comments_path(@user)}");

  .clear.vertical_spacer